apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: layer7
resources:
  - ./namespace.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: ssg-security-override-secret
    files:
      - "./properties/ssg.security"